name: Build Tauri App

on:
  push:
    tags:
      - "v*"

jobs:
  build-linux:
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 26
          cache: npm

      - name: Install frontend dependencies
        run: npm ci

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: Install Tauri CLI
        run: cargo install tauri-cli --version 2.11.4

      - name: Build Tauri app
        run: cargo tauri build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: src-tauri/target/release/bundle/appimage/*.AppImage